### ISSUE TITLE
Enhancement: persistent tray icon

### ISSUE THREAD

**Issue by ipgu7igi** [nmaier/mintrayr#151]
I'd like my Mozilla application to stay out of the window list, since I'm running it more often than not. Residing in the tray, ideally single click would open and close, as with Audacious and several other Linux applications. It would be even more of a space and hassle saver!

**Comment by jarau-de** [comment]
Yes, since firetray doesn't work anymore, I'm looking for an alternative for Linux and Firefox/Thunderbird. My wish is the same behaviour like Firetray. That means: single click for show and hide. This implicates a static icon in tray. Please! Another annoying thing is that the Firefox window does not restore at the same place on multi monitor environments. If that would work, I would be really happy.

**Comment by RAWRR** [comment]
I'd also love to see this behavior as a default. I really don't need my browser cluttering up the window list!

**Comment by RAWRR** [comment]
@nmaier

Closed because fixed or closed because wontfix? Definitely still care about this.
